name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the actual behavior...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Code Snippets
      description: If applicable, add screenshots or code snippets to help explain the problem.
      placeholder: Paste screenshots or code here...
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using? (e.g., Chrome 120, Firefox 121, Safari 17)
      placeholder: Chrome 120
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using? (e.g., Windows 11, macOS 14, Ubuntu 22.04)
      placeholder: Windows 11
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...
    validations:
      required: false
