name: Enhancement
description: Suggest an improvement to an existing feature
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement! Please fill out the form below to help us understand your suggestion.

  - type: textarea
    id: description
    attributes:
      label: Enhancement Description
      description: A clear and concise description of the enhancement you'd like to see.
      placeholder: Describe the enhancement...
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: How does the feature currently work?
      placeholder: Describe the current behavior...
    validations:
      required: true

  - type: textarea
    id: proposed-behavior
    attributes:
      label: Proposed Behavior
      description: How would you like the feature to work after the enhancement?
      placeholder: Describe the proposed behavior...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this enhancement provide? Who would benefit from it?
      placeholder: Describe the benefits...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Code Snippets
      description: If applicable, add screenshots or code snippets to illustrate the enhancement.
      placeholder: Paste screenshots or code here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the enhancement.
      placeholder: Any additional information...
    validations:
      required: false
